DBHost: "localhost"
DBPort: "3306"
DBUser: "root"
DBPassword: "YOUR_PASSWORD"
DBName: "notification_service"
RedisAddress: "localhost:6379"
KafkaBrokers: "localhost:9092"
ElasticSearchURL: "http://localhost:9200"
